import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="fixed w-full flex items-center justify-between p-4 border-b-2">
          <div id="logo"><a href="/">Newstarlity</a></div>
          <nav>
            <ul className="flex flex-row">
              <li className="mr-4">
                <a>정치</a>
              </li>
              <li>
                <a>사회</a>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
