# Generated by Django 5.0.4 on 2024-06-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_id", models.IntegerField(verbose_name="기사 ID")),
                ("content", models.TextField()),
                ("password", models.CharField(max_length=20)),
            ],
        ),
    ]
